# Generated by Django 2.0.3 on 2018-03-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('ic_code', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_students',
                'ordering': ('create_time',),
                'managed': False,
            },
        ),
    ]
